version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html # Map frontend to Nginx root
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  backend:
    build: ./backend
    deploy:
      mode: replicated
      replicas: 2 # This runs 2 instances of the backend
    ports:
      - "3000-3001:3000" # Exposes multiple instances
    environment:
      - PORT=3000
